version: '3'
services:
  my-libreoffice-service:
    build:
      context: ./doc2txt
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ${TYPESENSE_DATA_DIR:-./typesense-data}:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
  api-server:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "5003:8081"
    expose:
      - 8080
    environment:
      - PORT=8081
      - TYPESENSE_HOST=typesense
      - FIRESTORE_EMULATOR_HOST=host.docker.internal:8080
      - FIREBASE_AUTH_EMULATOR_HOST=host.docker.internal:9099
      - GCLOUD_PROJECT=taiwan-legislative-search
