version: '3'
services:
  my-libreoffice-service:
    build:
      context: ./doc2txt
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'
