name: Deploy Services to Google Cloud
on:
  workflow_run:
    workflows: ['Unit Tests on Push']
    types:
      - completed
    branches:
      - main
  workflow_dispatch:
env:
  LOCATION: asia-east1
  # Service that requires access to Gemini needs to be deployed in this location
  GEMINI_LOCATION: us-central1
jobs:
  detect_changes:
    runs-on: ubuntu-latest
    name: Detect Changes
    outputs:
      any_changes_api: ${{ steps.changed-api-files.outputs.any_changed }}
      any_changes_dataflow: ${{ steps.changed-dataflow-files.outputs.any_changed }}
      any_changes_functions: ${{ steps.changed-functions-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - name: Get changed API files
        id: changed-api-files
        uses: tj-actions/changed-files@v45
        with:
          files: 'cloudrun/api-server/**'
      - name: Get changed Dataflow files
        id: changed-dataflow-files
        uses: tj-actions/changed-files@v45
        with:
          files: 'dataflow/**'
      - name: Get changed functions files
        id: changed-functions-files
        uses: tj-actions/changed-files@v45
        with:
          files: 'functions/**'
  build_and_deploy_api_server:
    runs-on: ubuntu-latest
    needs: detect_changes
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy-api-server
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.detect_changes.outputs.any_changes_api == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v2'
      - env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo $GITHUB_CONTEXT
      - run: gcloud builds submit --region=$LOCATION
        working-directory: ./cloudrun/api-server

  buid_and_deploy_dataflow:
    runs-on: ubuntu-latest
    needs: detect_changes
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy-dataflow
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.detect_changes.outputs.any_changes_dataflow == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v2'
      - run: gcloud builds submit --region=$GEMINI_LOCATION --config=./dataflow/cloudbuild.yml

  build_and_deploy_firebase_functions:
    runs-on: ubuntu-latest
    needs: detect_changes
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-deploy-functions
      cancel-in-progress: true
    if: ${{ github.event.workflow_run.conclusion == 'success' && needs.detect_changes.outputs.any_changes_functions == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
      - uses: 'google-github-actions/setup-gcloud@v2'
      # Setup Python and virtual environment
      - uses: actions/setup-python@v5
        with:
         python-version: '3.12'
         cache: 'pip'
      - run: python3.12 -m venv venv
        working-directory: functions
      - run: source ./venv/bin/activate && python3.12 -m pip install -r requirements.txt
        working-directory: functions
      - run: pip install -r functions/requirements.txt
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only=functions
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAIWAN_LEGISLATIVE_SEARCH }}
      - run: gcloud builds submit --region=$GEMINI_LOCATION
        working-directory: ./functions
