name: Unit Tests on Push
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
env:
  FIRESTORE_EMULATOR_HOST: "127.0.0.1:8080"
  FIREBASE_AUTH_EMULATOR_HOST: "127.0.0.1:9099"
  FIREBASE_STORAGE_EMULATOR_HOST: "127.0.0.1:9199"
  STORAGE_EMULATOR_HOST: "http://127.0.0.1:9199"
  FIREBASE_EMULATOR_HUB: "127.0.0.1:4400"
  FUNCTIONS_EMULATOR_HOST: "127.0.0.1:5001"
  NETWORK_TEST: 0
jobs:
  test_firebase_functions:
    services:
      typesense:
        image: typesense/typesense:26.0
        ports:
          - 8108:8108
        volumes:
          - /data
        env:
          TYPESENSE_DATA_DIR: /data
          TYPESENSE_API_KEY: xyz
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/setup-python@v5
        with:
         python-version: '3.12'
         cache: 'pip'
      - uses: Iamshankhadeep/setup-ffmpeg@v1.2
        with:
          version: "4.4"
      - id: 'auth'
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.UNITTESTS_CREDENTIAL }}'
          export_environment_variables: true
      - run: npm install -g firebase-tools
      - run: python3.12 -m venv venv
        working-directory: functions
      - run: source ./venv/bin/activate && python3.12 -m pip install -r requirements.txt
        working-directory: functions
      - run: pip install -r functions/requirements.txt
      - run: |
          cat << EOF > .env
            FIRESTORE_EMULATOR_HOST=$FIRESTORE_EMULATOR_HOST
            FIREBASE_AUTH_EMULATOR_HOST=$FIREBASE_AUTH_EMULATOR_HOST
            FIREBASE_STORAGE_EMULATOR_HOST=$FIREBASE_STORAGE_EMULATOR_HOST
            STORAGE_EMULATOR_HOST=$STORAGE_EMULATOR_HOST
            FIREBASE_EMULATOR_HUB=$FIREBASE_EMULATOR_HUB
            FUNCTIONS_EMULATOR_HOST=$FUNCTIONS_EMULATOR_HOST
            GCLOUD_PROJECT=$GCLOUD_PROJECT
            GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS
          EOF
      - run: |
          cat << EOF > functions/.secret.local
          TYPESENSE_API_KEY=xyz
          EOF
      - run : |
          cat << EOF > functions/.env.local
          TYPESENSE_HOST=127.0.0.1
          TYPESENSE_PORT=8108
          TYPESENSE_PROTOCOL=http
          EOF
      - run: firebase experiments:enable webframeworks
      - run: firebase emulators:exec --only=auth,functions,firestore,storage pytest
